import { AnalyticsEvent, IndustryId } from "@/lib/projectSchema";

export const baseAnalyticsEvents: AnalyticsEvent[] = [
  {
    id: "demo_opened",
    name: "demo_opened",
    group: "Discovery",
    trigger: "User opens generated demo website",
    properties: ["projectId", "industry", "client"],
    businessPurpose: "Measures demo consumption and pre-sales engagement.",
    priority: "P1",
    owner: "Pre-sales",
  },
  {
    id: "apex_opened",
    name: "apex_opened",
    group: "Discovery",
    trigger: "Visitor opens APEX experience from page trigger",
    properties: ["projectId", "mode", "journeyContext"],
    businessPurpose: "Measures experience entry by mode and context.",
    priority: "P0",
    owner: "Growth / Analytics",
  },
  {
    id: "mode_selected",
    name: "mode_selected",
    group: "Discovery",
    trigger: "Demo user switches between Overlay, Assist, and Page modes",
    properties: ["projectId", "selectedMode", "previousMode"],
    businessPurpose: "Compares mode value in demos and final recommendations.",
    priority: "P1",
    owner: "Product",
  },
  {
    id: "intent_detected",
    name: "intent_detected",
    group: "Discovery",
    trigger: "User chooses journey intent or chip",
    properties: ["projectId", "journeyId", "intent"],
    businessPurpose: "Tracks intent mix and guides phase prioritization.",
    priority: "P0",
    owner: "Growth / CRM",
  },
  {
    id: "journey_selected",
    name: "journey_selected",
    group: "Journey",
    trigger: "Visitor selects a journey card or assistant suggestion",
    properties: ["projectId", "journeyId", "phase"],
    businessPurpose: "Tracks journey demand before implementation.",
    priority: "P0",
    owner: "Growth",
  },
  {
    id: "journey_started",
    name: "journey_started",
    group: "Journey",
    trigger: "User answers first contextual journey question",
    properties: ["projectId", "journeyId", "mode"],
    businessPurpose: "Measures journey initiation quality.",
    priority: "P0",
    owner: "Growth / Product",
  },
  {
    id: "question_answered",
    name: "question_answered",
    group: "Journey",
    trigger: "Any qualifying question receives a response",
    properties: ["projectId", "journeyId", "questionId", "state"],
    businessPurpose: "Identifies friction points in qualification flow.",
    priority: "P1",
    owner: "Analytics",
  },
  {
    id: "field_captured",
    name: "field_captured",
    group: "Journey",
    trigger: "A lead field is captured and validated",
    properties: ["projectId", "journeyId", "fieldName", "piiLevel"],
    businessPurpose: "Shows data readiness for CRM handoff.",
    priority: "P0",
    owner: "CRM / Analytics",
  },
  {
    id: "lead_score_updated",
    name: "lead_score_updated",
    group: "Qualification",
    trigger: "Score model is recalculated after each step",
    properties: ["projectId", "journeyId", "leadScore", "threshold"],
    businessPurpose: "Monitors qualification progression.",
    priority: "P0",
    owner: "Growth / CRM",
  },
  {
    id: "qualification_threshold_reached",
    name: "qualification_threshold_reached",
    group: "Qualification",
    trigger: "Lead score reaches or exceeds threshold",
    properties: ["projectId", "journeyId", "leadScore", "threshold"],
    businessPurpose: "Tracks score-gated conversion readiness.",
    priority: "P0",
    owner: "Growth / CRM",
  },
  {
    id: "consent_captured",
    name: "consent_captured",
    group: "Qualification",
    trigger: "User gives explicit consent for CRM or WhatsApp handoff",
    properties: ["projectId", "journeyId", "consentType", "channel"],
    businessPurpose: "Ensures compliant handoff measurement.",
    priority: "P0",
    owner: "Compliance / CRM",
  },
  {
    id: "lead_qualified",
    name: "lead_qualified",
    group: "Qualification",
    trigger: "Required fields plus consent captured and score >= 70",
    properties: ["projectId", "industry", "journeyId", "leadScore", "productType", "city", "handoffDestination"],
    businessPurpose: "Measures conversion from website intent to sales-ready lead.",
    priority: "P0",
    owner: "Growth / CRM / Analytics",
  },
  {
    id: "crm_push_attempted",
    name: "crm_push_attempted",
    group: "Handoff",
    trigger: "System attempts to push structured lead payload",
    properties: ["projectId", "journeyId", "destination", "attemptId"],
    businessPurpose: "Tracks integration dependency and payload readiness.",
    priority: "P0",
    owner: "Engineering / CRM",
  },
  {
    id: "crm_push_simulated",
    name: "crm_push_simulated",
    group: "Handoff",
    trigger: "Simulated CRM push returns success in prototype mode",
    properties: ["projectId", "journeyId", "destination", "result"],
    businessPurpose: "Demonstrates expected production handoff behavior.",
    priority: "P0",
    owner: "Pre-sales / Engineering",
  },
  {
    id: "whatsapp_handoff_started",
    name: "whatsapp_handoff_started",
    group: "Handoff",
    trigger: "Lead qualifies and WhatsApp continuation is prepared",
    properties: ["projectId", "journeyId", "templateId", "channel"],
    businessPurpose: "Tracks continuation channel readiness.",
    priority: "P1",
    owner: "CRM / Messaging",
  },
  {
    id: "advisor_callback_requested",
    name: "advisor_callback_requested",
    group: "Handoff",
    trigger: "User requests a human advisor callback",
    properties: ["projectId", "journeyId", "preferredSlot", "reason"],
    businessPurpose: "Captures high-intent human escalation demand.",
    priority: "P1",
    owner: "Sales",
  },
  {
    id: "handoff_completed",
    name: "handoff_completed",
    group: "Handoff",
    trigger: "CRM push and follow-up channel handoff finish",
    properties: ["projectId", "journeyId", "channels", "result"],
    businessPurpose: "Confirms end-to-end conversion completion.",
    priority: "P0",
    owner: "CRM / Analytics",
  },
  {
    id: "fallback_triggered",
    name: "fallback_triggered",
    group: "Fallback",
    trigger: "Required field missing or confidence falls below threshold",
    properties: ["projectId", "journeyId", "reason", "state"],
    businessPurpose: "Shows where qualification flow needs refinement.",
    priority: "P1",
    owner: "Product",
  },
  {
    id: "human_handoff_requested",
    name: "human_handoff_requested",
    group: "Fallback",
    trigger: "Guardrail or regulated advice trigger escalates to advisor",
    properties: ["projectId", "journeyId", "triggerType", "severity"],
    businessPurpose: "Ensures safe escalation path tracking.",
    priority: "P0",
    owner: "Compliance / Support",
  },
  {
    id: "dropoff_detected",
    name: "dropoff_detected",
    group: "Fallback",
    trigger: "User abandons journey before qualification",
    properties: ["projectId", "journeyId", "dropoffStep", "mode"],
    businessPurpose: "Measures conversion leak points in early phases.",
    priority: "P1",
    owner: "Growth",
  },
  {
    id: "integration_failure_simulated",
    name: "integration_failure_simulated",
    group: "Fallback",
    trigger: "Simulated push fails and fallback queue path activates",
    properties: ["projectId", "journeyId", "integration", "fallbackPath"],
    businessPurpose: "Validates resilience and ownership in production planning.",
    priority: "P1",
    owner: "Engineering",
  },
];

export function getAnalyticsForIndustry(industryId: IndustryId) {
  if (industryId === "insurance") {
    return baseAnalyticsEvents;
  }

  return baseAnalyticsEvents.map((event) => ({
    ...event,
    properties: event.properties.filter((property) => property !== "productType"),
  }));
}
