import { Guardrail, Industry, JourneyTemplate } from "@/lib/projectSchema";

const bankingGuardrails: Guardrail[] = [
  {
    id: "bank-no-loan-guarantee",
    label: "No guaranteed loan approval",
    description: "Do not guarantee loan approval or sanctioned amount.",
    severity: "High",
    fallbackBehavior: "State final approval depends on bank verification and policy.",
  },
  {
    id: "bank-no-investment-advice",
    label: "No investment advice",
    description: "Do not provide regulated investment advice.",
    severity: "High",
    fallbackBehavior: "Escalate to official bank advisory channels.",
  },
  {
    id: "bank-sensitive-data",
    label: "No sensitive credential collection",
    description: "Never collect OTP, PIN, passwords, CVV, or full bank credentials.",
    severity: "High",
    fallbackBehavior: "Stop flow and display secure-channel guidance.",
  },
  {
    id: "bank-dispute-escalation",
    label: "Dispute and fraud escalation",
    description: "Escalate disputes, fraud concerns, and account-sensitive actions to official bank channels.",
    severity: "High",
    fallbackBehavior: "Provide branch or helpline escalation options.",
  },
];

const journeys: JourneyTemplate[] = [
  {
    id: "bank-account-opening",
    industryId: "banking",
    name: "Account Opening",
    intent: "User wants to open a bank account",
    userProblem: "Users do not know account type fit and required prep.",
    businessValue: "High-value acquisition path.",
    whyRecommended: "Directly tied to new customer growth.",
    qualificationCriteria: ["Account type", "Location", "Phone", "KYC readiness", "Consent"],
    requiredFields: ["Account type", "Location", "Phone", "KYC readiness", "Consent"],
    optionalFields: ["Preferred branch"],
    recommendedCTA: "Start account opening",
    crmEvent: "account_opening_lead",
    suggestedMode: "APEX Overlay",
    complexity: "Medium",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: bankingGuardrails.map((g) => g.label),
    handoff: ["CRM", "Branch onboarding"],
    productionDependencies: ["KYC checklist API", "Branch routing"],
    sampleConversation: ["What account type are you planning to open?"],
    samplePayload: { event: "account_opening_lead" },
  },
  {
    id: "bank-loan-eligibility",
    industryId: "banking",
    name: "Loan Eligibility",
    intent: "User wants loan eligibility estimate",
    userProblem: "Users are unsure whether they meet basic criteria.",
    businessValue: "High-intent credit lead generation.",
    whyRecommended: "Captures demand early with minimal input.",
    qualificationCriteria: ["Loan type", "Income range", "Employment type", "City", "Phone", "Consent"],
    requiredFields: ["Loan type", "Income range", "Employment type", "City", "Phone", "Consent"],
    optionalFields: ["Credit score range"],
    recommendedCTA: "Check eligibility",
    crmEvent: "loan_eligibility_lead",
    suggestedMode: "APEX Assist",
    complexity: "Medium",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: bankingGuardrails.map((g) => g.label),
    handoff: ["CRM", "Loan desk"],
    productionDependencies: ["Eligibility engine", "Compliance messaging"],
    sampleConversation: ["Which type of loan are you looking for?"],
    samplePayload: { event: "loan_eligibility_lead" },
  },
  {
    id: "bank-credit-card-discovery",
    industryId: "banking",
    name: "Credit Card Discovery",
    intent: "User wants best-fit credit card",
    userProblem: "Card comparison is unclear for benefits and eligibility.",
    businessValue: "Improves card acquisition quality.",
    whyRecommended: "Personalized discovery improves conversion.",
    qualificationCriteria: ["Spend category", "Income range", "Benefit preference", "Phone", "Consent"],
    requiredFields: ["Spend category", "Income range", "Benefit preference", "Phone", "Consent"],
    optionalFields: ["Current cards"],
    recommendedCTA: "Find matching card",
    crmEvent: "credit_card_discovery_lead",
    suggestedMode: "APEX Page",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 2",
    guardrails: bankingGuardrails.map((g) => g.label),
    handoff: ["CRM", "Card sales"],
    productionDependencies: ["Card catalog", "Eligibility matrix"],
    sampleConversation: ["What spending category matters most to you?"],
    samplePayload: { event: "credit_card_discovery_lead" },
  },
  {
    id: "bank-kyc-checklist",
    industryId: "banking",
    name: "KYC / Document Checklist",
    intent: "User needs KYC document guidance",
    userProblem: "Users abandon due to unclear documentation requirements.",
    businessValue: "Reduces application drop-offs.",
    whyRecommended: "Simple operational journey with clear value.",
    qualificationCriteria: ["Product selected", "User type", "Location"],
    requiredFields: ["Product", "User type", "Location"],
    optionalFields: ["Language"],
    recommendedCTA: "View document checklist",
    crmEvent: "kyc_checklist_requested",
    suggestedMode: "APEX Assist",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: bankingGuardrails.map((g) => g.label),
    handoff: ["CRM"],
    productionDependencies: ["Document policy list"],
    sampleConversation: ["Which product KYC checklist do you need?"],
    samplePayload: { event: "kyc_checklist_requested" },
  },
  {
    id: "bank-branch-callback",
    industryId: "banking",
    name: "Branch / Callback Routing",
    intent: "User wants branch help or callback",
    userProblem: "Users cannot quickly find branch-level assistance.",
    businessValue: "Captures service intent and improves assisted conversion.",
    whyRecommended: "Useful fallback when digital self-serve stalls.",
    qualificationCriteria: ["City/area", "Product interest", "Phone", "Preferred time", "Consent"],
    requiredFields: ["City/area", "Product interest", "Phone", "Preferred time", "Consent"],
    optionalFields: ["Branch preference"],
    recommendedCTA: "Request callback",
    crmEvent: "branch_callback_requested",
    suggestedMode: "APEX Overlay",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: bankingGuardrails.map((g) => g.label),
    handoff: ["CRM", "Branch queue"],
    productionDependencies: ["Branch list", "Queue routing"],
    sampleConversation: ["Which area should we route your callback to?"],
    samplePayload: { event: "branch_callback_requested" },
  },
  {
    id: "bank-application-status",
    industryId: "banking",
    name: "Application Status",
    intent: "User wants status updates",
    userProblem: "Users rely on support calls for status checks.",
    businessValue: "Improves service efficiency and user trust.",
    whyRecommended: "Post-submission utility path for retention.",
    qualificationCriteria: ["Application ID or phone", "Product type"],
    requiredFields: ["Application ID or phone", "Product type"],
    optionalFields: ["DOB month/year"],
    recommendedCTA: "Track application",
    crmEvent: "application_status_request",
    suggestedMode: "APEX Assist",
    complexity: "Medium",
    feasibility: "Medium",
    phase: "Phase 2",
    guardrails: bankingGuardrails.map((g) => g.label),
    handoff: ["CRM", "Status API"],
    productionDependencies: ["Status endpoint", "Case fallback"],
    sampleConversation: ["Please share your application ID or registered phone."],
    samplePayload: { event: "application_status_request" },
  },
  {
    id: "bank-product-comparison",
    industryId: "banking",
    name: "Product Comparison",
    intent: "User wants to compare product options",
    userProblem: "Product pages do not support structured comparison decisions.",
    businessValue: "Improves advisor-ready qualified leads.",
    whyRecommended: "Captures exploratory users with conversion intent.",
    qualificationCriteria: ["Product category", "User priorities", "Consent if handed off"],
    requiredFields: ["Product category", "User priorities"],
    optionalFields: ["Phone"],
    recommendedCTA: "Compare products",
    crmEvent: "product_comparison_lead",
    suggestedMode: "APEX Page",
    complexity: "Medium",
    feasibility: "High",
    phase: "Phase 2",
    guardrails: bankingGuardrails.map((g) => g.label),
    handoff: ["CRM", "Advisor"],
    productionDependencies: ["Product matrix", "Rate table"],
    sampleConversation: ["Which product type should we compare first?"],
    samplePayload: { event: "product_comparison_lead" },
  },
];

export const bankingIndustryPack: Industry = {
  id: "banking",
  name: "Banking",
  description: "Conversion journeys for banking product discovery and assisted onboarding.",
  recommendedGoals: [
    "Increase qualified leads",
    "Improve product discovery",
    "Improve branch/location routing",
    "Reduce drop-offs before contact capture",
  ],
  defaultGoal: "Increase qualified banking leads for account and loan journeys",
  defaultConversionAction: "Submit qualified lead",
  defaultClientName: "Summit Trust Bank",
  defaultWebsite: "https://www.summittrust.example",
  defaultPage: "https://www.summittrust.example/open-account",
  defaultOwner: "Banking Solution Team",
  defaultTargetSegment: "Retail customers evaluating financial products",
  journeys,
  guardrails: bankingGuardrails,
  defaultIntegrations: ["engati-crm", "rest-api", "knowledge-upload", "custom-webhook", "website-ingestion"],
  analyticsEvents: ["lead_qualified", "human_handoff_requested", "handoff_completed"],
};
