import { Guardrail, Industry, JourneyTemplate } from "@/lib/projectSchema";

const edtechGuardrails: Guardrail[] = [
  {
    id: "edu-no-admission-guarantee",
    label: "No guaranteed admission",
    description: "Do not guarantee admission outcomes.",
    severity: "High",
    fallbackBehavior: "Mark recommendations as informational and subject to official review.",
  },
  {
    id: "edu-no-scholarship-guarantee",
    label: "No guaranteed scholarship",
    description: "Do not guarantee scholarship approval.",
    severity: "Medium",
    fallbackBehavior: "Provide requirements and encourage counsellor follow-up.",
  },
  {
    id: "edu-no-misleading-placement",
    label: "No misleading placement claims",
    description: "Avoid misleading placement or salary assurances.",
    severity: "High",
    fallbackBehavior: "Reference published outcomes only.",
  },
  {
    id: "edu-data-minimization",
    label: "Student data minimization",
    description: "Collect only data needed for qualification and routing.",
    severity: "Medium",
    fallbackBehavior: "Prompt minimal educational profile until intent is clear.",
  },
];

const journeys: JourneyTemplate[] = [
  {
    id: "ed-course-discovery",
    industryId: "edtech",
    name: "Course Discovery",
    intent: "User wants best-fit course",
    userProblem: "Users are unsure which program matches their goal and level.",
    businessValue: "Improves discovery-to-enquiry conversion.",
    whyRecommended: "Top funnel with direct impact on qualified enquiry volume.",
    qualificationCriteria: ["Education level", "Goal", "Subject/program", "Timeline"],
    requiredFields: ["Education level", "Goal", "Preferred subject", "Timeline"],
    optionalFields: ["Location", "Preferred format"],
    recommendedCTA: "Find best-fit course",
    crmEvent: "course_discovery_lead",
    suggestedMode: "APEX Overlay",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: edtechGuardrails.map((g) => g.label),
    handoff: ["CRM"],
    productionDependencies: ["Course catalog mapping"],
    sampleConversation: ["What learning outcome are you targeting?"],
    samplePayload: { event: "course_discovery_lead" },
  },
  {
    id: "ed-eligibility-check",
    industryId: "edtech",
    name: "Eligibility Check",
    intent: "User wants eligibility clarity",
    userProblem: "Eligibility criteria is often unclear before applying.",
    businessValue: "Filters low-fit leads and improves advisor efficiency.",
    whyRecommended: "Strong mid-funnel qualification path.",
    qualificationCriteria: ["Academic background", "Score range", "Location", "Target program"],
    requiredFields: ["Academic background", "Score range", "Target program", "Location"],
    optionalFields: ["Entrance test status"],
    recommendedCTA: "Check eligibility",
    crmEvent: "eligibility_check_lead",
    suggestedMode: "APEX Assist",
    complexity: "Medium",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: edtechGuardrails.map((g) => g.label),
    handoff: ["CRM", "Counsellor"],
    productionDependencies: ["Eligibility rule engine"],
    sampleConversation: ["Which program are you targeting?"],
    samplePayload: { event: "eligibility_check_lead" },
  },
  {
    id: "ed-fee-scholarship",
    industryId: "edtech",
    name: "Fee / Scholarship Explanation",
    intent: "User needs fee clarity and scholarship options",
    userProblem: "Cost concerns block application starts.",
    businessValue: "Reduces drop-off due to fee uncertainty.",
    whyRecommended: "Improves trust and application progression.",
    qualificationCriteria: ["Program selected", "Fee concern captured", "Scholarship interest"],
    requiredFields: ["Program", "Fee concern", "Scholarship interest"],
    optionalFields: ["Phone", "Funding preference"],
    recommendedCTA: "View fee and scholarship options",
    crmEvent: "fee_scholarship_enquiry",
    suggestedMode: "APEX Page",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 2",
    guardrails: edtechGuardrails.map((g) => g.label),
    handoff: ["CRM", "Counsellor"],
    productionDependencies: ["Fee matrix", "Scholarship policy"],
    sampleConversation: ["Which program fee would you like to review?"],
    samplePayload: { event: "fee_scholarship_enquiry" },
  },
  {
    id: "ed-counsellor-callback",
    industryId: "edtech",
    name: "Counsellor Callback",
    intent: "User wants human guidance",
    userProblem: "Users need confidence before committing.",
    businessValue: "High-quality lead capture via counsellor handoff.",
    whyRecommended: "Recovers uncertain users into callback pipeline.",
    qualificationCriteria: ["Name", "Phone", "Preferred time", "Program interest", "Consent"],
    requiredFields: ["Name", "Phone", "Preferred time", "Program", "Consent"],
    optionalFields: ["Current education"],
    recommendedCTA: "Schedule counsellor callback",
    crmEvent: "counsellor_callback_requested",
    suggestedMode: "APEX Assist",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: edtechGuardrails.map((g) => g.label),
    handoff: ["CRM", "Counsellor desk"],
    productionDependencies: ["Callback slot scheduling"],
    sampleConversation: ["What should the counsellor help you with first?"],
    samplePayload: { event: "counsellor_callback_requested" },
  },
  {
    id: "ed-application-start",
    industryId: "edtech",
    name: "Application Start",
    intent: "User wants to begin application",
    userProblem: "Users abandon when application starts without guidance.",
    businessValue: "Improves application start rate.",
    whyRecommended: "Directly tied to admissions funnel volume.",
    qualificationCriteria: ["Program selected", "Contact captured", "Eligibility basics", "Consent"],
    requiredFields: ["Program", "Phone/email", "Eligibility basics", "Consent"],
    optionalFields: ["Preferred campus"],
    recommendedCTA: "Start application",
    crmEvent: "application_start_lead",
    suggestedMode: "APEX Overlay",
    complexity: "Medium",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: edtechGuardrails.map((g) => g.label),
    handoff: ["CRM", "Application API"],
    productionDependencies: ["Application endpoint", "Document checklist"],
    sampleConversation: ["Which program should we start the application for?"],
    samplePayload: { event: "application_start_lead" },
  },
  {
    id: "ed-brochure-download",
    industryId: "edtech",
    name: "Brochure Download",
    intent: "User wants downloadable brochure",
    userProblem: "Brochure pages capture little qualification context.",
    businessValue: "Converts content downloads into qualified nurture leads.",
    whyRecommended: "Quick win for inbound campaign traffic.",
    qualificationCriteria: ["Program selected", "Email/phone", "Consent"],
    requiredFields: ["Program", "Email/phone", "Consent"],
    optionalFields: ["Preferred intake"],
    recommendedCTA: "Download brochure",
    crmEvent: "brochure_download_lead",
    suggestedMode: "APEX Page",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 2",
    guardrails: edtechGuardrails.map((g) => g.label),
    handoff: ["CRM", "Email automation"],
    productionDependencies: ["Asset links", "Consent capture"],
    sampleConversation: ["Which brochure should I send?"],
    samplePayload: { event: "brochure_download_lead" },
  },
  {
    id: "ed-deadline-reminder",
    industryId: "edtech",
    name: "Deadline Reminder",
    intent: "User wants intake deadline reminders",
    userProblem: "Users miss deadlines and return later with low intent.",
    businessValue: "Improves reactivation and deadline adherence.",
    whyRecommended: "Useful retention tactic for interested prospects.",
    qualificationCriteria: ["Program selected", "Preferred channel", "Date interest"],
    requiredFields: ["Program", "Preferred channel", "Date/deadline"],
    optionalFields: ["Phone"],
    recommendedCTA: "Set reminder",
    crmEvent: "deadline_reminder_set",
    suggestedMode: "APEX Assist",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 2",
    guardrails: edtechGuardrails.map((g) => g.label),
    handoff: ["CRM", "Notification service"],
    productionDependencies: ["Notification templates"],
    sampleConversation: ["Which program deadline should we remind you about?"],
    samplePayload: { event: "deadline_reminder_set" },
  },
];

export const edtechIndustryPack: Industry = {
  id: "edtech",
  name: "Edtech",
  description: "Student acquisition and application progression journeys.",
  recommendedGoals: [
    "Improve product discovery",
    "Increase qualified leads",
    "Improve application start rate",
    "Improve callback capture",
  ],
  defaultGoal: "Increase qualified student leads and improve application starts",
  defaultConversionAction: "Start application",
  defaultClientName: "SkillBridge Academy",
  defaultWebsite: "https://www.skillbridge.example",
  defaultPage: "https://www.skillbridge.example/programs",
  defaultOwner: "Education Growth Team",
  defaultTargetSegment: "Undergraduate and working professional learners",
  journeys,
  guardrails: edtechGuardrails,
  defaultIntegrations: ["engati-crm", "whatsapp-business", "rest-api", "knowledge-upload", "google-sheets"],
  analyticsEvents: ["lead_qualified", "application_started", "brochure_downloaded"],
};
