import { Guardrail, Industry, JourneyTemplate } from "@/lib/projectSchema";

const healthcareGuardrails: Guardrail[] = [
  {
    id: "health-no-diagnosis",
    label: "No diagnosis",
    description: "Do not diagnose conditions. Route users to specialists based on symptoms only.",
    severity: "High",
    fallbackBehavior: "Prompt for consultation booking or emergency care guidance.",
  },
  {
    id: "health-no-prescription",
    label: "No medication prescription",
    description: "Do not prescribe medication or treatment plans.",
    severity: "High",
    fallbackBehavior: "Recommend consultation with licensed clinician.",
  },
  {
    id: "health-emergency-route",
    label: "Emergency escalation",
    description: "Emergency symptoms should route immediately to emergency care.",
    severity: "High",
    fallbackBehavior: "Display emergency guidance and emergency contact instructions.",
  },
  {
    id: "health-data-minimization",
    label: "Data minimization",
    description: "Do not collect unnecessary medical history before intent clarity.",
    severity: "Medium",
    fallbackBehavior: "Collect only booking-related details and consent.",
  },
];

const journeys: JourneyTemplate[] = [
  {
    id: "health-specialty-discovery",
    industryId: "healthcare",
    name: "Specialty Discovery",
    intent: "User needs help choosing the right specialty",
    userProblem: "Users know symptoms but not clinical specialty.",
    businessValue: "Improves navigation and appointment conversion.",
    whyRecommended: "Reduces drop-off from uncertainty at top of funnel.",
    qualificationCriteria: ["Symptom category", "Urgency", "Location", "Phone", "Consent"],
    requiredFields: ["Symptom/care category", "Urgency level", "Preferred location", "Phone", "Consent"],
    optionalFields: ["Preferred gender", "Insurance coverage"],
    recommendedCTA: "Find right specialist",
    crmEvent: "specialty_discovery_lead",
    suggestedMode: "APEX Overlay",
    complexity: "Medium",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: healthcareGuardrails.map((g) => g.label),
    handoff: ["CRM", "Appointment desk"],
    productionDependencies: ["Specialty taxonomy", "Location mapping", "Scheduling integration"],
    sampleConversation: ["What care need should we route for?", "How urgent is this request?"],
    samplePayload: { event: "specialty_discovery_lead", urgency: "Within 24h" },
  },
  {
    id: "health-consultation-booking",
    industryId: "healthcare",
    name: "Consultation Booking",
    intent: "User wants to book an appointment",
    userProblem: "Scheduling is often fragmented by specialty and location.",
    businessValue: "Direct booking conversion and operational efficiency.",
    whyRecommended: "High intent path tied to revenue outcomes.",
    qualificationCriteria: ["Specialty", "Location", "Date/time", "Phone", "Consent"],
    requiredFields: ["Specialty", "Location", "Preferred date/time", "Phone", "Consent"],
    optionalFields: ["Doctor preference"],
    recommendedCTA: "Book consultation",
    crmEvent: "consultation_booking_lead",
    suggestedMode: "APEX Assist",
    complexity: "Medium",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: healthcareGuardrails.map((g) => g.label),
    handoff: ["CRM", "Calendar"],
    productionDependencies: ["Calendar API", "Slot rules"],
    sampleConversation: ["Which specialty should we book for?", "What time works for you?"],
    samplePayload: { event: "consultation_booking_lead", specialty: "Cardiology" },
  },
  {
    id: "health-location-routing",
    industryId: "healthcare",
    name: "Location Routing",
    intent: "User wants nearest care center",
    userProblem: "Users cannot identify the best center for a given service quickly.",
    businessValue: "Improves branch conversion and reduces call center load.",
    whyRecommended: "Fast routing supports both care and operations.",
    qualificationCriteria: ["City/area", "Service type", "Preferred distance/time"],
    requiredFields: ["City/area", "Service type"],
    optionalFields: ["Preferred distance/time"],
    recommendedCTA: "Show nearest center",
    crmEvent: "location_routing_request",
    suggestedMode: "APEX Page",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: healthcareGuardrails.map((g) => g.label),
    handoff: ["Location engine"],
    productionDependencies: ["Branch/location dataset"],
    sampleConversation: ["Which city should we search in?"],
    samplePayload: { event: "location_routing_request", city: "Bengaluru" },
  },
  {
    id: "health-package-enquiry",
    industryId: "healthcare",
    name: "Package / Service Enquiry",
    intent: "User wants package details",
    userProblem: "Package pages lack guided follow-up capture.",
    businessValue: "Captures intent for elective or preventive packages.",
    whyRecommended: "Converts passive content browsing into enquiry leads.",
    qualificationCriteria: ["Package selected", "User details", "Location", "Consent"],
    requiredFields: ["Package/service", "Phone", "Location", "Consent"],
    optionalFields: ["Preferred date"],
    recommendedCTA: "Request package details",
    crmEvent: "package_enquiry_lead",
    suggestedMode: "APEX Overlay",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 2",
    guardrails: healthcareGuardrails.map((g) => g.label),
    handoff: ["CRM"],
    productionDependencies: ["Package catalog"],
    sampleConversation: ["Which package are you interested in?"],
    samplePayload: { event: "package_enquiry_lead" },
  },
  {
    id: "health-callback-capture",
    industryId: "healthcare",
    name: "Callback Capture",
    intent: "User wants call assistance",
    userProblem: "Users need reassurance before booking.",
    businessValue: "Recovers uncertain visitors into qualified callbacks.",
    whyRecommended: "Useful fallback when booking is not completed.",
    qualificationCriteria: ["Name", "Phone", "Concern", "Preferred callback time", "Consent"],
    requiredFields: ["Name", "Phone", "Concern", "Preferred callback time", "Consent"],
    optionalFields: ["Language"],
    recommendedCTA: "Request callback",
    crmEvent: "callback_capture",
    suggestedMode: "APEX Assist",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 2",
    guardrails: healthcareGuardrails.map((g) => g.label),
    handoff: ["CRM", "Call center"],
    productionDependencies: ["Callback routing"],
    sampleConversation: ["What should the care team help you with?"],
    samplePayload: { event: "callback_capture" },
  },
  {
    id: "health-appointment-followup",
    industryId: "healthcare",
    name: "Appointment Follow-up",
    intent: "User needs appointment updates or changes",
    userProblem: "Users struggle with reschedule/cancel flows.",
    businessValue: "Improves retention and reduces support tickets.",
    whyRecommended: "Operational support path with clear demand.",
    qualificationCriteria: ["Appointment ID or phone", "Requested action"],
    requiredFields: ["Appointment ID or phone", "Action"],
    optionalFields: ["Reason"],
    recommendedCTA: "Manage appointment",
    crmEvent: "appointment_followup_request",
    suggestedMode: "APEX Assist",
    complexity: "Medium",
    feasibility: "Medium",
    phase: "Phase 2",
    guardrails: healthcareGuardrails.map((g) => g.label),
    handoff: ["CRM", "Appointment system"],
    productionDependencies: ["Appointment status API"],
    sampleConversation: ["Please share appointment ID or registered phone."],
    samplePayload: { event: "appointment_followup_request" },
  },
];

export const healthcareIndustryPack: Industry = {
  id: "healthcare",
  name: "Healthcare",
  description: "Guided patient acquisition and service routing journeys.",
  recommendedGoals: [
    "Improve appointment booking",
    "Increase qualified leads",
    "Improve branch/location routing",
    "Improve self-service resolution",
  ],
  defaultGoal: "Improve appointment booking and reduce pre-booking drop-offs",
  defaultConversionAction: "Book consultation",
  defaultClientName: "NorthStar Care",
  defaultWebsite: "https://www.northstarcare.example",
  defaultPage: "https://www.northstarcare.example/book",
  defaultOwner: "Healthcare Solutions",
  defaultTargetSegment: "Urban care seekers and follow-up patients",
  journeys,
  guardrails: healthcareGuardrails,
  defaultIntegrations: ["engati-crm", "rest-api", "calendar-system", "knowledge-upload"],
  analyticsEvents: ["appointment_booked", "lead_qualified", "human_handoff_requested"],
};
