import { Guardrail, Industry, JourneyTemplate } from "@/lib/projectSchema";

const insuranceGuardrails: Guardrail[] = [
  {
    id: "ins-no-policy-approval",
    label: "No guaranteed policy approval",
    description: "Do not guarantee policy approval. Final underwriting depends on insurer systems.",
    severity: "High",
    fallbackBehavior: "Inform user that final approval depends on official checks and offer advisor callback.",
  },
  {
    id: "ins-no-premium-guarantee",
    label: "No guaranteed premium",
    description: "Do not guarantee premium amount before insurer validation.",
    severity: "High",
    fallbackBehavior: "Provide indicative ranges and route user to quote flow.",
  },
  {
    id: "ins-no-claim-guarantee",
    label: "No guaranteed claim settlement",
    description: "Do not guarantee claim settlement timelines or outcomes.",
    severity: "High",
    fallbackBehavior: "Route claim disputes or escalations to human advisor.",
  },
  {
    id: "ins-sensitive-data-limit",
    label: "Sensitive data limits",
    description: "Do not ask for OTP, card PIN, CVV, passwords, or unnecessary sensitive data.",
    severity: "High",
    fallbackBehavior: "Mask identifiers and ask only required qualification fields.",
  },
  {
    id: "ins-regulated-advice",
    label: "Regulated advice escalation",
    description: "Do not provide legal, tax, or regulated financial advice.",
    severity: "Medium",
    fallbackBehavior: "Escalate to licensed human advisor with context summary.",
  },
  {
    id: "ins-consent-first",
    label: "Consent before handoff",
    description: "Capture explicit consent before CRM or WhatsApp handoff.",
    severity: "High",
    fallbackBehavior: "If consent missing, store as partial lead and continue on-site guidance.",
  },
];

const insuranceJourneys: JourneyTemplate[] = [
  {
    id: "insurance-get-quote",
    industryId: "insurance",
    name: "Get Quote",
    intent: "User wants a new insurance quote",
    userProblem: "User cannot quickly identify product-fit and gets blocked by long forms.",
    businessValue: "Highest commercial intent and strongest path to qualified quote leads.",
    whyRecommended: "Intent is high on quote pages. Progressive qualification improves completion and routing.",
    qualificationCriteria: [
      "Product type selected",
      "City/location captured",
      "Phone number captured",
      "Consent captured",
      "Product-specific detail captured",
    ],
    requiredFields: ["Product type", "City", "Phone number", "Consent", "Product-specific detail"],
    optionalFields: ["Email", "Preferred callback time", "Existing policy status", "Budget range"],
    recommendedCTA: "Get personalized quote",
    crmEvent: "qualified_quote_lead",
    suggestedMode: "APEX Overlay",
    complexity: "Medium",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: insuranceGuardrails.map((g) => g.label),
    handoff: ["Engati CRM", "WhatsApp Business"],
    productionDependencies: [
      "CRM lead object mapping",
      "WhatsApp template approval",
      "Quote API optional for Phase 2",
      "Compliance approval for product copy",
    ],
    sampleConversation: [
      "Great choice. What type of insurance are you looking for?",
      "For motor insurance, do you have the vehicle registration number, or prefer make/model/year?",
      "Which city are you in?",
      "Please share the best phone number for quote follow-up.",
      "Can we use this information to continue in CRM and WhatsApp?",
    ],
    samplePayload: {
      event: "qualified_quote_lead",
      productType: "Motor insurance",
      city: "Mumbai",
      leadScore: 90,
      handoff: ["Engati CRM", "WhatsApp Business"],
      consent: true,
    },
  },
  {
    id: "insurance-renew-policy",
    industryId: "insurance",
    name: "Renew Policy",
    intent: "User wants to renew an existing policy",
    userProblem: "Returning customers struggle to locate renewal entry points quickly.",
    businessValue: "High-intent returning path with strong close-rate potential.",
    whyRecommended: "Renewal intent is frequent on policy landing pages and needs fast routing.",
    qualificationCriteria: [
      "Policy number or vehicle registration captured",
      "Phone number captured",
      "Renewal due date or status captured",
      "Consent captured",
    ],
    requiredFields: ["Policy number or vehicle registration", "Phone number", "Consent"],
    optionalFields: ["Renewal due date", "Preferred callback window"],
    recommendedCTA: "Continue renewal",
    crmEvent: "policy_renewal_lead",
    suggestedMode: "APEX Overlay",
    complexity: "Medium",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: insuranceGuardrails.map((g) => g.label),
    handoff: ["Engati CRM", "Advisor queue"],
    productionDependencies: ["Policy lookup API", "CRM renewal mapping", "Compliance copy review"],
    sampleConversation: [
      "I can help with renewal. Do you have your policy number or vehicle registration?",
      "What is your renewal due date?",
      "Please share a phone number for renewal confirmation.",
    ],
    samplePayload: {
      event: "policy_renewal_lead",
      policyRef: "MH12AB1234",
      renewalDueDate: "2026-06-10",
      consent: true,
    },
  },
  {
    id: "insurance-advisor-callback",
    industryId: "insurance",
    name: "Advisor Callback",
    intent: "User wants human help",
    userProblem: "Not all users are ready to self-serve, but they still have buying intent.",
    businessValue: "Captures high-intent leads that otherwise abandon quote forms.",
    whyRecommended: "Early callback offers recover uncertain users without forcing form completion.",
    qualificationCriteria: ["Name", "Phone number", "Preferred callback time", "Intent reason", "Consent captured"],
    requiredFields: ["Name", "Phone number", "Preferred callback time", "Consent"],
    optionalFields: ["Policy context", "Preferred language"],
    recommendedCTA: "Schedule advisor callback",
    crmEvent: "advisor_callback_requested",
    suggestedMode: "APEX Assist",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 1",
    guardrails: insuranceGuardrails.map((g) => g.label),
    handoff: ["Engati CRM", "Advisor desk"],
    productionDependencies: ["Callback scheduling rules", "Agent availability routing"],
    sampleConversation: [
      "I can schedule a callback. What should the advisor help you with?",
      "Which time works best for you?",
    ],
    samplePayload: {
      event: "advisor_callback_requested",
      callbackSlot: "Tomorrow 11:00",
      reason: "Need help selecting motor plan",
      consent: true,
    },
  },
  {
    id: "insurance-track-claim",
    industryId: "insurance",
    name: "Track Claim",
    intent: "User wants claim status",
    userProblem: "Users want updates quickly but often lack claim context in one place.",
    businessValue: "Supports service experience while preserving upsell/cross-sell trust.",
    whyRecommended: "Adds post-sale utility and captures service intent for routing.",
    qualificationCriteria: [
      "Claim number or policy number captured",
      "Registered phone/email captured",
      "User informed final status depends on insurer systems",
    ],
    requiredFields: ["Claim number or policy number", "Registered phone/email"],
    optionalFields: ["Incident date", "Claim type"],
    recommendedCTA: "Check claim status",
    crmEvent: "claim_tracking_request",
    suggestedMode: "APEX Assist",
    complexity: "Medium",
    feasibility: "Medium",
    phase: "Phase 2",
    guardrails: [
      "Never guarantee claim approval or settlement amount",
      "Escalate disputes to official support channel",
      "Mask sensitive identifiers",
    ],
    handoff: ["CRM case", "Support desk"],
    productionDependencies: ["Claim status API", "Case management integration"],
    sampleConversation: [
      "I can help track your claim. Please share claim number or policy number.",
      "I will route this to the claim support workflow.",
    ],
    samplePayload: {
      event: "claim_tracking_request",
      claimRef: "CLM-20391",
      userContact: "+91XXXXXXXXXX",
    },
  },
  {
    id: "insurance-compare-plans",
    industryId: "insurance",
    name: "Compare Plans",
    intent: "User is exploring options and wants help choosing",
    userProblem: "Users struggle to compare plans without structured guidance.",
    businessValue: "Improves early-funnel discovery quality and advisor efficiency.",
    whyRecommended: "Intent-first comparison reduces form fatigue and improves product fit.",
    qualificationCriteria: [
      "Product type selected",
      "Budget range captured",
      "Coverage need captured",
      "Phone if advisor follow-up requested",
      "Consent if pushed to CRM/WhatsApp",
    ],
    requiredFields: ["Product type", "Budget range", "Coverage need"],
    optionalFields: ["Phone number", "Existing insurer", "Renewal month"],
    recommendedCTA: "Compare recommended options",
    crmEvent: "plan_comparison_lead",
    suggestedMode: "APEX Page",
    complexity: "Medium",
    feasibility: "High",
    phase: "Phase 2",
    guardrails: [
      "Do not give regulated financial advice",
      "Present comparisons as informational",
      "Escalate detailed recommendation request to advisor",
    ],
    handoff: ["CRM", "Advisor callback"],
    productionDependencies: ["Plan catalog feed", "Eligibility rules"],
    sampleConversation: [
      "Let us compare options. Which insurance type do you want?",
      "What budget range feels right?",
      "Would you like advisor guidance on shortlisted plans?",
    ],
    samplePayload: {
      event: "plan_comparison_lead",
      productType: "Health insurance",
      budgetRange: "15K-25K",
      consent: true,
    },
  },
  {
    id: "insurance-policy-copy",
    industryId: "insurance",
    name: "Policy Copy / Document Request",
    intent: "User needs policy document, receipt, or certificate",
    userProblem: "Document requests are often hidden inside service portals.",
    businessValue: "Improves retention and reduces support queue volume.",
    whyRecommended: "Low-complexity quick win for post-sale service.",
    qualificationCriteria: [
      "Policy number or phone captured",
      "Document type selected",
      "Preferred delivery channel selected",
      "Consent captured",
    ],
    requiredFields: ["Policy number or phone", "Document type", "Delivery channel", "Consent"],
    optionalFields: ["Email", "Urgency"],
    recommendedCTA: "Send policy copy",
    crmEvent: "document_request",
    suggestedMode: "APEX Assist",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 2",
    guardrails: ["Mask policy identifiers", "Do not expose sensitive account data"],
    handoff: ["CRM", "Document service"],
    productionDependencies: ["Document API", "Notification channel templates"],
    sampleConversation: [
      "I can help send your policy copy. Which document do you need?",
      "How should we deliver it, SMS or email?",
    ],
    samplePayload: {
      event: "document_request",
      documentType: "Policy certificate",
      channel: "Email",
    },
  },
  {
    id: "insurance-addons",
    industryId: "insurance",
    name: "Add-ons / Riders Discovery",
    intent: "User wants add-ons like zero depreciation or riders",
    userProblem: "Add-on value is not obvious inside standard quote forms.",
    businessValue: "Improves AOV and upsell readiness.",
    whyRecommended: "Simple discovery flow increases value without heavy integration.",
    qualificationCriteria: [
      "Base product selected",
      "Add-on interest captured",
      "Policy/new quote context captured",
      "Consent if handed off",
    ],
    requiredFields: ["Base product", "Add-on interest"],
    optionalFields: ["Policy context", "Phone"],
    recommendedCTA: "Explore add-ons",
    crmEvent: "addon_interest_lead",
    suggestedMode: "APEX Page",
    complexity: "Low",
    feasibility: "High",
    phase: "Phase 2",
    guardrails: ["Do not overpromise coverage", "Mark add-ons as policy-dependent"],
    handoff: ["CRM", "Advisor routing"],
    productionDependencies: ["Add-on catalog", "Eligibility matrix"],
    sampleConversation: [
      "Which add-ons are you curious about?",
      "I can route these preferences to an advisor for final recommendation.",
    ],
    samplePayload: {
      event: "addon_interest_lead",
      addOns: ["Zero depreciation", "Roadside assistance"],
      consent: true,
    },
  },
];

export const insuranceIndustryPack: Industry = {
  id: "insurance",
  name: "Insurance",
  description: "Conversion journeys for quote, renewal, service, and advisor-assisted insurance flows.",
  recommendedGoals: [
    "Increase qualified leads",
    "Improve quote completion",
    "Improve callback capture",
    "Improve WhatsApp continuation",
    "Reduce drop-offs before contact capture",
  ],
  defaultGoal: "Increase qualified insurance leads and improve quote/renewal completion",
  defaultConversionAction: "Generate qualified quote lead",
  defaultClientName: "NovaSure Insurance",
  defaultWebsite: "https://www.novasure.example",
  defaultPage: "https://www.novasure.example/get-quote",
  defaultOwner: "Engati Solutions Team",
  defaultTargetSegment: "Retail insurance shoppers and policy renewals",
  journeys: insuranceJourneys,
  guardrails: insuranceGuardrails,
  defaultIntegrations: ["engati-crm", "whatsapp-business", "rest-api", "knowledge-upload", "website-ingestion"],
  analyticsEvents: [
    "lead_qualified",
    "crm_push_simulated",
    "whatsapp_handoff_started",
    "dropoff_detected",
  ],
};
